### PR TITLE
Plt 8561/automate two users

### PR DESCRIPTION
**Pull request by ladamesny**

### CODE REVIEW

**Comment by paluh** [comment]
Thanks a lot @ladamesny! I will merge this as it is but we can discuss if we really want to keep both `js` and `ts` files in the repo.

**Comment by paluh** [comment]
Actually is it ready to merge?

**Comment by ladamesny** [comment]
@paluh we should merge the other PR first. I'll keep this in wip until we do some. The diff should be much smaller.

**Comment by paluh** [comment]
I'm closing because iteration over this branch with multiple improvements was already merged in #29.

**Pull request closed without merging**
