### PR TITLE
PLT-7563 Docker images

### PR DESCRIPTION
**Pull request by bwbush**
@zeme-wana, @shlevy, @paluh, basd on our Sept 27 conversation, I created the bash script [make-docker-image.sh](https://github.com/input-output-hk/marlowe-runner/blob/PLT-7563/make-docker-image.sh) that does the spago and webpack builds (from inside the `nix develop` shell) and then creates a Docker image.

The [Dockerfile](https://github.com/input-output-hk/marlowe-runner/blob/PLT-7563/Dockerfile) uses `sed` to edit in the correct `MARLOWE_WEB_SERVER_URL` just before launching `darkhttpd`.

Please review to see that this is sufficient for an interim deployment via docker.

### CODE REVIEW

**Comment by paluh** [comment]
Thanks a lot Brian. I will merge this version as it is but if you have some comments Guys please add them here.

> The Dockerfile uses sed to edit in the correct MARLOWE_WEB_SERVER_URL just before launching darkhttpd.

@zeme-wana, @shlevy - can we leave it like that or should I introduce some simple config file which should be added to the app dir and overrides default value?

**Comment by shlevy** [comment]
I think a config file would ultimately be nicer, but this will work for now.

**Comment by shlevy** [comment]
Do we need a similar way to override the network name? Or is that inferred now?

**Comment by paluh** [comment]
@shlevy the network is now inferred from the runtime `/healthcheck` response headers.

**Pull request merged**
