### PR TITLE
Add links to playground and scanner

### PR DESCRIPTION
**Pull request by hrajchert**
This PR adds links to the Playground and Scanner from the Details view

Screenshot 2023-11-07 at 22 52 08

### CODE REVIEW

**Review by palas — APPROVED** [review]
Thank you, looks good! The only thing is that I think @paluh was suggesting it only showed on debug mode, I am not sure if this requirement changed

**Comment by hrajchert** [comment]
I think it should always be shown as it is useful information that doesn't include debug info

**Comment by paluh** [comment]
@palas I suggested debug for non approved features when we implemented them rushing to the Summit. If we agree that this version can be included I don't think we should hide it behind any flag.
I will merge this today I think. Sorry for the delay

**Comment by paluh** [comment]
Thanks @hrajchert!

**Pull request merged**
